---
- name: 'set sudoers'
  community.general.sudoers:
    name: 'cog'
    user: 'cog'
    commands: ALL
    nopassword: true

- name: 'set sudoers'
  community.general.sudoers:
    name: 'fierce_brake'
    user: 'fierce_brake'
    commands: 'ALL'
    nopassword: false

